version: "3.9"
services:
  postgresql:
    image: 'postgres:15.2'
    container_name: bilhed-database
    environment:
      - POSTGRES_DB=bilhed
      - POSTGRES_USER=bilhed
      - POSTGRES_PASSWORD=bilhed
    ports:
      - '5432:5432'

  rabbitmq:
    image: 'rabbitmq:3.11-management'
    container_name: bilhed-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=bilhed
      - RABBITMQ_DEFAULT_PASS=bilhed
    ports:
      - '5672:5672'
      - '15672:15672'