version: "3.9"
services:
  postgresql:
    image: 'postgres:15.2'
    container_name: bilhed-database
    environment:
      - POSTGRES_DB=bilhed
      - POSTGRES_USER=bilhed
      - POSTGRES_PASSWORD=bilhed
    ports:
      - '5432:5432'