version: "3.9"
services:
  mariadb:
    image: 'mariadb:10.5.10'
    container_name: mariadb-bilhed
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bilhed
      - MYSQL_USER=bilhed
      - MYSQL_PASSWORD=bilhed
    ports:
      - '3306:3306'