spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bilhed
    username: bilhed
    password: bilhed

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "bilhed"
    password: "bilhed"

server.port: 4006

bilhed.back:
  participantFrontUrl: http://localhost:5000
  breizhCampYear: 2025

  registerCloseDate: 2025-06-15T23:59:59+02:00
  breizhCampCloseDate: 2025-06-28T23:59:59+02:00

  billetWeb.enabled: false

  bihan:
    url: http://localhost:4010
    apiKey: 1234567890
