spring:
  liquibase.changeLog: classpath:/db/changelog/db.changelog-master.xml

  security.oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://auth.breizhcamp.org/auth/realms/BreizhCamp
        jwk-set-uri: https://auth.breizhcamp.org/auth/realms/BreizhCamp/protocol/openid-connect/certs


logging.level.reactor.netty.http.client: DEBUG

bilhed.back:
  participantFrontUrl: https://billets.breizhcamp.org

  passNumber:
    TWO_DAYS: 170
    THREE_DAYS: 160

  bihan:
    url: https://bzh.camp

  billetWeb:
    url: https://www.billetweb.fr/

    passNames:
      TWO_DAYS: "Billet > Pass 2 jours"
      THREE_DAYS: "Billet > Pass 3 jours"