spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bilhed
    username: bilhed
    password: bilhed

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "bilhed"
    password: "bilhed"

server.port: 4006

bilhed.back:
  participantFrontUrl: http://localhost:5000
  breizhCampYear: 2024

  registerCloseDate: 2024-06-15T23:59:59+02:00
  breizhCampCloseDate: 2024-06-28T23:59:59+02:00

  billetWeb.enabled: false
