spring:
  mail:
    host: localhost
    port: 1025

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "bilhed"
    password: "bilhed"

server.port: 4008

bilhed.mail:
  from:
    name: "Billetterie BreizhCamp"
    email: billetterie@breizhcamp.org